# SITE CONFIGURATION
title: South West Communities
author: Future Sync Events
baseurl: "" # the subpath of the site, e.g. /blog
url: "" # the base hostname & protocol for the site, e.g. http://example.com

# SEO PLUGIN
social:
  name: South West Communities
  links:
    - https://twitter.com/SWCommunities
    - https://instagram.com/SWCommunities
    - https://www.facebook.com/SWCommunities

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Communities', link: '/communities/', description: 'A list of community led organisations hosting events in the region.', featured-img: 'communities'}
  - {name: 'Calendar', link: '/calendar/', description: 'A constantly updated calendar of events by communities around the South West.', featured-img: 'calendar'}
  - {name: 'Call for Proposals', link: '/proposals/', description: 'Submit a talk via our shared call for proposals system.', featured-img: 'proposals'}
  # - {name: 'Resources', link: '/resources/', description: 'Discover some useful resources for people runing events', featured-img: 'sleek'}

tagline: >
  A shared events calendar for grassroots digital and tech communities across the South West

hero_img: posts/header_lg.jpg # Main background image: use the path from /assets/img/

twitter_username: SWCommunities
# facebook_username: SWCommunities
instagram_username: SWCommunities

google_tag_manager: UA-92339313-2
facebook_pixel: 796127733884814

service_worker: false

# BUILD SETTINGS
markdown: kramdown

exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  communities:
    output: true
  resources:
    output: false
  events:
    output: true
  proposals:
    output: true
